[package]
name = "please"
version = "0.1.0"
authors = ["a <no@no.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpassword = "0.0.4"
rs-crypt = { git = "https://github.com/aibhstin/rscrypt", branch = "main" }
